### ISSUE TITLE
Add support for yanking maven release

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/build_utilities#35]
Currently demote-to-stable only takes care of yanking installers from s3. We need to yank a release from the maven repo if something goes wrong

**Comment by ketan** [comment]
I don't believe yanking maven releases has been allowed for quite some time — https://stackoverflow.com/questions/9789611/removing-an-artifact-from-maven-central

**Comment by varshavaradarajan** [comment]
Yes, I think we resort to recreating the artifact. That should be fine I suppose in case anything goes wrong.
